### ISSUE TITLE
User account is not created

### ISSUE THREAD

**Issue by roger-net** [syltmedia/FOSSBilling_KeyHelp#1]
First, I want to congratulate you for the initiative to create a module for KeyHelp, which I consider to be a sensational panel.
I installed it on my FossBilling and I believe I made the settings correctly but it doesn't create the user account on my KeyHelp. I set up the api key, I click the button to test the connection and it shows "server connected". FossBilling sends access data by email but KeyHelp does not create an account.

**Comment by syltmedia** [comment]
Hello Rogério,
I forget to write that the package in FOSSBilling must be the ID of the package in KeyHelp. That's a work in progress.

**Comment by syltmedia** [comment]
fixed in the v0.0.2 ;)
